meta_name: "Taste, don't waste"
meta_title: "Taste, don't waste | Fast and easy recipes to help preventing food waste"
meta_description: "A way to find recipes with the ingredients that you have at home"
meta_image: "logo-meta.png" # should exist in `app/assets/images/`
