meta_name: "Taste, don't waste"
meta_title: "Taste, don't waste - Fast and easy recipe ideas to help you waste less food"
meta_description: "A way to find recipes with the ingredients that you have at home"
meta_image: "logo.png" # should exist in `app/assets/images/`

